title: USA 2.0
description: A shared blueprint for improving how the country works.
baseurl: "/usa2.0"
url: "https://aaronbclark.github.io"
markdown: kramdown
permalink: pretty

collections:
  sections:
    output: true
    permalink: /sections/:name/

defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: section

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
